default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: santa_development 

test: &test
  <<: *default
  database: santa_test

production: &production
  <<: *default
  database: santa_on_rails
  username: santa
  password: hohoho


cucumber:
  <<: *test